/**
 * UI Styles for the application
 * This file contains component-specific style combinations built from uiConstants
 */

import {
  COLORS,
  TEXT,
  FONT,
  SPACING,
  BORDER,
  SHADOW,
  TRANSITION,
  EFFECTS,
  COMPONENTS,
  LAYOUT
} from './uiConstants';

// Common reusable styles across components
export const COMMON_STYLES = {
  // Layout
  FLEX_CENTER: LAYOUT.FLEX.CENTER,
  FLEX_BETWEEN: 'flex justify-between items-center',
  FLEX_COLUMN: LAYOUT.FLEX.COLUMN,
  FLEX_ROW: LAYOUT.FLEX.ROW,
  CONTAINER: LAYOUT.CONTAINER,
  
  // Typography
  FONT_BOLD: FONT.WEIGHT.BOLD,
  FONT_SEMIBOLD: FONT.WEIGHT.SEMIBOLD,
  FONT_MEDIUM: FONT.WEIGHT.MEDIUM,
  FONT_SM: FONT.SIZE.SM,
  FONT_LG: FONT.SIZE.LG,
  FONT_XL: FONT.SIZE.XL,
  TEXT_PRIMARY: TEXT.PRIMARY,
  TEXT_SECONDARY: TEXT.SECONDARY,
  TEXT_TERTIARY: TEXT.TERTIARY,
  TEXT_WHITE: 'text-white',
  
  // Spacing
  MARGIN_TOP_SM: SPACING.MARGIN.TOP.SM,
  MARGIN_TOP_MD: SPACING.MARGIN.TOP.MD,
  MARGIN_BOTTOM_SM: SPACING.MARGIN.BOTTOM.SM,
  MARGIN_BOTTOM_MD: SPACING.MARGIN.BOTTOM.MD,
  MARGIN_BOTTOM_LG: SPACING.MARGIN.BOTTOM.LG,
  MARGIN_BOTTOM_XL: SPACING.MARGIN.BOTTOM.XL,
  MARGIN_TOP_XL: SPACING.MARGIN.TOP.XL,
  PADDING_SM: SPACING.SM,
  PADDING_MD: SPACING.MD,
  PADDING_LG: SPACING.LG,
  PADDING_X_MD: SPACING.PADDING.X.MD,
  PADDING_Y_SM: SPACING.PADDING.Y.SM,
  GAP_SM: SPACING.GAP.SM,
  GAP_XS: SPACING.GAP.XS,
  
  // Borders & Effects
  ROUNDED: BORDER.RADIUS.DEFAULT,
  ROUNDED_MD: BORDER.RADIUS.MD,
  ROUNDED_LG: BORDER.RADIUS.LG,
  ROUNDED_FULL: BORDER.RADIUS.FULL,
  SHADOW_MD: SHADOW.MD,
  SHADOW_SM: SHADOW.SM,
  TRANSITION_BASE: TRANSITION.DEFAULT,
  TRANSITION_COLORS: TRANSITION.COLORS,
  
  // Common UI Patterns
  CARD_BASE: COMPONENTS.CARD.DEFAULT,
  CARD_HOVER: COMPONENTS.CARD.HOVER,
  CARD_FULL: COMPONENTS.CARD.FULL,
  BUTTON_PRIMARY: COMPONENTS.BUTTON.PRIMARY,
  BUTTON_SECONDARY: COMPONENTS.BUTTON.SECONDARY,
  BUTTON_DISABLED: COMPONENTS.BUTTON.DISABLED,
  LOADING_SPINNER: COMPONENTS.LOADING.SPINNER,
  LOADING_SKELETON: COMPONENTS.LOADING.SKELETON,
  MODAL_OVERLAY: COMPONENTS.MODAL.OVERLAY,
  
  // Common combined patterns
  HEADING_LG: `${FONT.SIZE.LG} ${FONT.WEIGHT.SEMIBOLD} ${TEXT.PRIMARY}`,
  HEADING_XL: `${FONT.SIZE.XL} ${FONT.WEIGHT.BOLD} ${TEXT.PRIMARY}`,
  HEADING_2XL: `${FONT.SIZE['2XL']} ${FONT.WEIGHT.BOLD} ${TEXT.PRIMARY}`,
  HEADING_3XL: `${FONT.SIZE['3XL']} ${FONT.WEIGHT.BOLD} ${TEXT.PRIMARY}`,
  BODY_TEXT: `${FONT.SIZE.BASE} ${TEXT.SECONDARY}`,
  BODY_TEXT_SM: `${FONT.SIZE.SM} ${TEXT.SECONDARY}`,
  FLEX_CENTER_COLUMN: `${LAYOUT.FLEX.CENTER} ${LAYOUT.FLEX.COLUMN}`,
  STANDARD_PADDING: `${SPACING.PADDING.X.MD} ${SPACING.PADDING.Y.MD}`,
  STANDARD_MARGIN: `${SPACING.MARGIN.X.MD} ${SPACING.MARGIN.Y.MD}`,
};

// Skeleton component styles - used across multiple components
export const SKELETON_STYLES = {
  BASE: `${COLORS.GRAY[300]} dark:${COLORS.GRAY[700]} ${BORDER.RADIUS.DEFAULT} ${SPACING.MARGIN.BOTTOM.XS}`,
  CONTAINER: `${COMMON_STYLES.CARD_BASE} ${COMMON_STYLES.LOADING_SKELETON}`,
  IMAGE: `h-48 ${COLORS.GRAY[300]} dark:${COLORS.GRAY[700]}`,
  TITLE: `h-4 ${COLORS.GRAY[300]} dark:${COLORS.GRAY[700]} ${BORDER.RADIUS.DEFAULT} ${SPACING.MARGIN.BOTTOM.XS} w-3/4`,
  SUBTITLE: `h-3 ${COLORS.GRAY[300]} dark:${COLORS.GRAY[700]} ${BORDER.RADIUS.DEFAULT} ${SPACING.MARGIN.BOTTOM.XS} w-1/2`,
  TEXT: `h-3 ${COLORS.GRAY[300]} dark:${COLORS.GRAY[700]} ${BORDER.RADIUS.DEFAULT} ${SPACING.MARGIN.BOTTOM.XS} w-full`,
};

// Button styles - used across multiple components
export const BUTTON_STYLES = {
  PRIMARY: COMMON_STYLES.BUTTON_PRIMARY,
  SECONDARY: COMMON_STYLES.BUTTON_SECONDARY,
  DISABLED: COMMON_STYLES.BUTTON_DISABLED,
  STANDARD: `${COMMON_STYLES.PADDING_X_MD} ${COMMON_STYLES.PADDING_Y_SM} ${COMMON_STYLES.ROUNDED}`,
  DANGER: `${COMMON_STYLES.PADDING_X_MD} ${COMMON_STYLES.PADDING_Y_SM} bg-red-600 hover:bg-red-700 text-white ${COMMON_STYLES.ROUNDED} ${COMMON_STYLES.TRANSITION_COLORS}`,
  SUCCESS: `${COMMON_STYLES.PADDING_X_MD} ${COMMON_STYLES.PADDING_Y_SM} bg-green-600 hover:bg-green-700 text-white ${COMMON_STYLES.ROUNDED} ${COMMON_STYLES.TRANSITION_COLORS}`,
  ICON: COMPONENTS.BUTTON.ICON,
};

// AnimeCard component styles
export const CARD_STYLES = {
  // Card structure
  CONTAINER: COMMON_STYLES.CARD_FULL,
  IMAGE_CONTAINER: 'relative aspect-[3/4] overflow-hidden',
  INFO_CONTAINER: COMMON_STYLES.PADDING_MD,
  
  // Image and trailer
  IMAGE: `object-cover ${TRANSITION.TRANSFORM} ${EFFECTS.HOVER.SCALE}`,
  TRAILER_OVERLAY: `absolute inset-0 ${COMMON_STYLES.FLEX_CENTER} bg-black/50 opacity-0 hover:opacity-100 ${TRANSITION.OPACITY}`,
  TRAILER_BUTTON: `${COMMON_STYLES.FLEX_CENTER} ${COMMON_STYLES.ROUNDED_FULL} ${COLORS.ACCENT.RED.DEFAULT} p-3 ${SHADOW.LG}`,
  PLAY_ICON: `h-6 w-6 ${COMMON_STYLES.TEXT_WHITE}`,
  
  // Title and info
  TITLE: `${COMMON_STYLES.HEADING_LG} line-clamp-2 ${SPACING.MARGIN.BOTTOM.XS}`,
  INFO_SECTION: `${COMMON_STYLES.FLEX_COLUMN} ${COMMON_STYLES.GAP_XS} ${COMMON_STYLES.MARGIN_BOTTOM_SM}`,
  
  // Format and metadata
  FORMAT_BADGE: `${COMMON_STYLES.FONT_SM} ${COMMON_STYLES.FONT_SEMIBOLD} ${TEXT.INVERTED} ${COLORS.PRIMARY[600]} ${SPACING.PADDING.X.XS} ${SPACING.PADDING.Y.XS} ${COMMON_STYLES.ROUNDED}`,
  TV_BADGE: `${COMMON_STYLES.FONT_SM} ${COMMON_STYLES.FONT_SEMIBOLD} ${TEXT.INVERTED} bg-blue-600 ${SPACING.PADDING.X.XS} ${SPACING.PADDING.Y.XS} ${COMMON_STYLES.ROUNDED}`,
  MOVIE_BADGE: `${COMMON_STYLES.FONT_SM} ${COMMON_STYLES.FONT_SEMIBOLD} ${TEXT.INVERTED} bg-purple-600 ${SPACING.PADDING.X.XS} ${SPACING.PADDING.Y.XS} ${COMMON_STYLES.ROUNDED}`,
  
  // Metadata row
  METADATA_ROW: `flex items-center justify-between ${COMMON_STYLES.MARGIN_BOTTOM_SM}`,
  DATE_TEXT: `${COMMON_STYLES.FONT_SM} ${COMMON_STYLES.TEXT_TERTIARY}`,
  POPULARITY_CONTAINER: `${COMMON_STYLES.FLEX_CENTER} ${COMMON_STYLES.FONT_SM} ${COMMON_STYLES.TEXT_TERTIARY}`,
  STAR_ICON: `${COLORS.ACCENT.YELLOW.TEXT} ${SPACING.MARGIN.X.XS}`,
  
  // Genres and tags
  TAGS_CONTAINER: `flex flex-wrap ${COMMON_STYLES.GAP_XS} ${SPACING.MARGIN.TOP.XS} ${COMMON_STYLES.MARGIN_BOTTOM_SM}`,
  GENRE_TAG: `${COMMON_STYLES.FONT_SM} ${COMMON_STYLES.TEXT_TERTIARY} ${COLORS.GRAY[100]} dark:${COLORS.GRAY[700]} ${SPACING.PADDING.X.XS} ${SPACING.PADDING.Y.XS} ${COMMON_STYLES.ROUNDED_FULL}`,
  DESCRIPTION: `${COMMON_STYLES.TEXT_TERTIARY} ${COMMON_STYLES.FONT_SM} line-clamp-3 ${COMMON_STYLES.MARGIN_TOP_SM}`,
  
  // Modal
  MODAL_CONTAINER: 'relative w-full max-w-3xl',
  CLOSE_BUTTON: `absolute -top-10 right-0 ${COMMON_STYLES.TEXT_WHITE} ${COMMON_STYLES.TRANSITION_COLORS} hover:text-gray-300`,
  VIDEO_CONTAINER: `relative aspect-video w-full ${COLORS.BLACK} ${COMMON_STYLES.ROUNDED} overflow-hidden`,
  IFRAME: 'absolute inset-0 w-full h-full',
  ERROR_CONTAINER: `absolute inset-0 ${COMMON_STYLES.FLEX_CENTER_COLUMN} justify-center ${COMMON_STYLES.TEXT_WHITE}`,
  ERROR_ICON: `${FONT.SIZE['3XL']} ${SPACING.MARGIN.BOTTOM.XS}`,
  YOUTUBE_BUTTON: `${COMMON_STYLES.MARGIN_TOP_MD} ${BUTTON_STYLES.DANGER}`,
};

// AnimeGrid component styles
export const GRID_STYLES = {
  EMPTY_STATE_CONTAINER: `${COMMON_STYLES.FLEX_CENTER_COLUMN} justify-center ${SPACING.PADDING.Y.XL} ${SPACING.PADDING.X.MD} text-center`,
  EMPTY_STATE_ICON: `w-24 h-24 ${COMMON_STYLES.TEXT_TERTIARY} ${COMMON_STYLES.MARGIN_BOTTOM_MD}`,
  EMPTY_STATE_TITLE: `${COMMON_STYLES.HEADING_XL} ${COMMON_STYLES.MARGIN_BOTTOM_SM}`,
  EMPTY_STATE_TEXT: `${COMMON_STYLES.TEXT_SECONDARY} max-w-md ${COMMON_STYLES.MARGIN_BOTTOM_LG}`,
  LIST_ITEM: COMMON_STYLES.MARGIN_BOTTOM_SM,
  SKELETON_ITEM: SKELETON_STYLES.CONTAINER,
  SKELETON_IMAGE: SKELETON_STYLES.IMAGE,
  SKELETON_TITLE: SKELETON_STYLES.TITLE,
  SKELETON_SUBTITLE: SKELETON_STYLES.SUBTITLE,
  SKELETON_TEXT: SKELETON_STYLES.TEXT,
  NOTICE_CONTAINER: `${COMMON_STYLES.MARGIN_BOTTOM_LG} ${COMMON_STYLES.PADDING_MD} ${COLORS.PRIMARY[50]} ${BORDER.DEFAULT} border-yellow-200 dark:border-yellow-900 ${COMMON_STYLES.ROUNDED_LG}`,
  NOTICE_TITLE: `${COMMON_STYLES.FONT_LG} ${COMMON_STYLES.FONT_MEDIUM} text-yellow-800 dark:text-yellow-200 ${COMMON_STYLES.MARGIN_BOTTOM_SM}`,
  NOTICE_TEXT: `text-yellow-700 dark:text-yellow-300`,
  ANIME_GRID: LAYOUT.GRID.COLS[4],
};

// Pagination component styles
export const PAGINATION_STYLES = {
  CONTAINER: `${COMMON_STYLES.FLEX_CENTER} ${COMMON_STYLES.MARGIN_TOP_XL} ${COMMON_STYLES.MARGIN_BOTTOM_XL} ${COMMON_STYLES.GAP_SM}`,
  BUTTONS_CONTAINER: `${COMMON_STYLES.FLEX_ROW} ${COMMON_STYLES.GAP_SM}`,
  ELLIPSIS: `${COMMON_STYLES.PADDING_X_MD} ${COMMON_STYLES.PADDING_Y_SM}`,
  PAGE_BUTTON: `${COMMON_STYLES.PADDING_X_MD} ${COMMON_STYLES.PADDING_Y_SM} ${COMMON_STYLES.ROUNDED_MD}`,
  ACTIVE_BUTTON: BUTTON_STYLES.PRIMARY,
  INACTIVE_BUTTON: BUTTON_STYLES.SECONDARY,
  DISABLED_BUTTON: BUTTON_STYLES.DISABLED,
};

// SortSelector component styles
export const SELECTOR_STYLES = {
  CONTAINER: `${COMMON_STYLES.FLEX_CENTER} ${COMMON_STYLES.GAP_SM}`,
  LABEL: `${COMMON_STYLES.FONT_SM} ${COMMON_STYLES.FONT_MEDIUM} ${COMMON_STYLES.TEXT_SECONDARY}`,
  SELECT: `${COLORS.WHITE} border ${BORDER.DEFAULT} ${COMMON_STYLES.TEXT_PRIMARY} ${COMMON_STYLES.FONT_SM} ${COMMON_STYLES.ROUNDED_LG} focus:ring-blue-500 focus:border-blue-500 ${COMMON_STYLES.PADDING_SM}`,
};

// LoadingSpinner component styles
export const SPINNER_STYLES = {
  CONTAINER: `${COMMON_STYLES.FLEX_CENTER_COLUMN} justify-center ${COMMON_STYLES.PADDING_LG}`,
  SPINNER: `${COMMON_STYLES.LOADING_SPINNER} rounded-full h-12 w-12 border-t-2 border-b-2 border-blue-500 ${COMMON_STYLES.MARGIN_BOTTOM_MD}`,
  MESSAGE: `${COMMON_STYLES.FONT_LG} ${COMMON_STYLES.TEXT_SECONDARY}`,
};

// ErrorDisplay component styles
export const ERROR_STYLES = {
  CONTAINER: `bg-red-100 dark:bg-red-900/30 border border-red-400 dark:border-red-800 text-red-700 dark:text-red-300 ${COMMON_STYLES.STANDARD_PADDING} ${COMMON_STYLES.ROUNDED_LG}`,
  CONTENT: `${COMMON_STYLES.FLEX_COLUMN} md:flex-row md:items-center md:justify-between`,
  MESSAGE_CONTAINER: `${COMMON_STYLES.MARGIN_BOTTOM_MD} md:mb-0`,
  TITLE: `${COMMON_STYLES.FONT_BOLD} ${COMMON_STYLES.FONT_LG} ${SPACING.MARGIN.BOTTOM.XS}`,
  ERROR_TEXT: COMMON_STYLES.FONT_SM,
  RETRY_BUTTON: BUTTON_STYLES.DANGER,
};

// ErrorBoundary component styles
export const ERROR_BOUNDARY_STYLES = {
  CONTAINER: `${COMMON_STYLES.PADDING_LG} bg-red-50 dark:bg-red-900/20 ${COMMON_STYLES.ROUNDED_LG} ${COMMON_STYLES.SHADOW_MD}`,
  TITLE: `${COMMON_STYLES.FONT_XL} ${COMMON_STYLES.FONT_BOLD} ${TEXT.ERROR} ${COMMON_STYLES.MARGIN_BOTTOM_SM}`,
  MESSAGE: `${COMMON_STYLES.TEXT_SECONDARY} ${COMMON_STYLES.MARGIN_BOTTOM_MD}`,
  DETAILS: `${COLORS.WHITE} ${COMMON_STYLES.PADDING_MD} ${COMMON_STYLES.ROUNDED_MD} ${COMMON_STYLES.SHADOW_SM}`,
  SUMMARY: `cursor-pointer ${TEXT.LINK} ${COMMON_STYLES.FONT_MEDIUM}`,
  PRE: `${COMMON_STYLES.MARGIN_TOP_SM} ${COMMON_STYLES.PADDING_SM} bg-gray-100 dark:bg-gray-900 ${COMMON_STYLES.ROUNDED} overflow-auto ${COMMON_STYLES.FONT_SM}`,
  BUTTON: `${COMMON_STYLES.MARGIN_TOP_MD} ${BUTTON_STYLES.PRIMARY}`,
};

// Page component styles
export const PAGE_STYLES = {
  CONTAINER: `min-h-screen ${COLORS.GRAY[100]}`,
  HEADER: `${COLORS.WHITE} ${COMMON_STYLES.SHADOW_MD}`,
  HEADER_CONTAINER: `${COMMON_STYLES.CONTAINER} ${SPACING.PADDING.Y.LG}`,
  TITLE: `${COMMON_STYLES.HEADING_3XL}`,
  SUBTITLE: `${COMMON_STYLES.MARGIN_TOP_SM} ${COMMON_STYLES.TEXT_SECONDARY}`,
  CONTROLS_ROW: `${COMMON_STYLES.FLEX_BETWEEN} ${COMMON_STYLES.MARGIN_BOTTOM_LG}`,
  SECTION_TITLE: `${COMMON_STYLES.HEADING_XL}`,
  GRID_CONTAINER: COMMON_STYLES.MARGIN_BOTTOM_XL,
  LOADING_INDICATOR: `${COMMON_STYLES.FLEX_CENTER} ${COMMON_STYLES.MARGIN_TOP_MD} ${COMMON_STYLES.MARGIN_BOTTOM_MD}`
}; 